#!/bin/bash
TIMEOUT=5
killall doozerd
./doozerd -timeout=$TIMEOUT -l 127.0.0.1:38046 -w=false 2>/dev/null &
MASTER_PID=$!
sleep 1
./doozerd -timeout=$TIMEOUT -l 127.0.0.1:38047 -a 127.0.0.1:38046 -w=false 2>/dev/null &
SLAVE1_PID=$!
sleep 1
printf '' | doozer -a="doozer:?ca=127.0.0.1:38046" set /ctl/cal/1 0
sleep 1
./doozerd -timeout=$TIMEOUT -l 127.0.0.1:38048 -a 127.0.0.1:38046 -w=false 2>/dev/null &
SLAVE2_PID=$!
sleep 1
printf '' | doozer -a="doozer:?ca=127.0.0.1:38046" set /ctl/cal/2 0
./doozerd -timeout=$TIMEOUT -l 127.0.0.1:38049 -a 127.0.0.1:38046 -w=false 2>/dev/null &
SLAVE2_PID=$!
sleep 1
printf '' | doozer -a="doozer:?ca=127.0.0.1:38046" set /ctl/cal/3 0
./doozerd -timeout=$TIMEOUT -l 127.0.0.1:38050 -a 127.0.0.1:38046 -w=false 2>/dev/null &
SLAVE2_PID=$!
sleep 1
printf '' | doozer -a="doozer:?ca=127.0.0.1:38046" set /ctl/cal/4 0

sleep 1
kill $MASTER_PID
echo "Killed the master doozerd ... go on debugging the shit out"
echo -e "\n\nMaster pid:\n\tkill $MASTER_PID\nto restart it:\n\t./doozerd -timeout=$TIMEOUT -l 127.0.0.1:38046 -a 127.0.0.1:38047 -w=false # or \n\t./doozerd -timeout=$TIMEOUT -l 127.0.0.1:38046 -a 127.0.0.1:38048 -w=false "
